# This is a basic workflow to help you get started with Actions

name: CD

on:
  push:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  pipeline:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout git repo
        uses: actions/checkout@v3
        with:
          ref: "main"
          fetch-depth: 0
      - name: Create SSH key
        run: |
          install -m 600 -D /dev/null ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          ssh-keyscan -H moochee.us > ~/.ssh/known_hosts
      - name: Deploy
        run: ./pipeline.sh
        env:
          ENV: "production"
          ADMIN_SECRET: ${{ secrets.ADMIN_SECRET }}
          DATABASE_TYPE: ${{ secrets.DATABASE_TYPE }}
          DATABASE_URL: "/auth/user.db"
          PORT: 8080
          AUTHORIZER_URL: "https://auth.moochee.us"
          DISABLE_BASIC_AUTHENTICATION: true
          ROLES: "free,pro"
          DEFAULT_ROLES: "free"
          JWT_ROLE_CLAIM: "role"
          COOKIE_NAME: "authorizer"
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET: ${{ secrets.GOOGLE_CLIENT_SECRET }}
